from supriya.contexts.entities import Bus as Bus
from supriya.contexts.entities import BusGroup as BusGroup

class ServerSHM:
    def __init__(self, port_number: int, bus_count: int) -> None: ...
    def describe_scope_buffer(self, index: int) -> tuple[int, int]: ...
    def read_scope_buffer(self, index: int) -> tuple[int, list[float]]: ...
    def __getitem__(
        self, item: Bus | BusGroup | int | slice
    ) -> float | list[float]: ...
    def __setitem__(
        self, item: Bus | BusGroup | int | slice, value: float | list[float]
    ) -> None: ...
