repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.30.0 # Zizmor version.
    hooks:
      # Run the linter.
      - id: zizmor
        args: [--no-progress, --fix]
  - repo: https://github.com/astral-sh/ruff-pre-commit

    rev: v0.16.5 # Ruff version.
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.3.0 # rstcheck version
    hooks:
      - id: rstcheck
        additional_dependencies: ['rstcheck[sphinx,toml]']
