#! /usr/bin/env python
# -*- encoding: utf-8 -*-
import os
print('Testing in: {}'.format(os.path.abspath(os.curdir)))

if __name__ == '__main__':
    from supriya.tools import scripttools
    script = scripttools.RunDoctestsScript()
    script()