name: Setup audio
description: Setup audio
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      name: (linux) Setup audio
      run: |
        sudo apt-get update
        sudo apt-get install --yes jackd2
        sudo usermod -a -G audio ${USER}
        sleep 5
        sudo -E su ${USER} -c "jackd -r -ddummy -r44100 -p1024" &
        sleep 5
      shell: bash
    - if: runner.os == 'macOS'
      name: (macos) Setup audio
      run: |
        brew install jack
        sleep 5
        sudo -E su ${USER} -c "jackd -r -ddummy -r44100 -p1024" &
        sleep 5
        system_profiler -json | jq .SPAudioDataType
      shell: bash
    - if: runner.os == 'Windows'
      name: (win32) Setup audio
      run: |
        choco install asio4all -y --no-progress
      shell: bash
