#! /usr/bin/env python
# -*- encoding: utf-8 -*-
from supriya.tools import servertools
from supriya.tools import webguitools


if __name__ == '__main__':
    from supriya.tools.systemtools.run_supriya_web import run_supriya_web
    run_supriya_web()