name: Setup audio under OSX
description: Setup audio under OSX
runs:
  using: "composite"
  steps:

    - name: Install jack
      run: brew install jack
      shell: bash

    - name: Setup Jack
      run: |
        echo "Setting up Jack..."
        sleep 5
        echo "Starting Jack..."
        sudo -E su ${USER} -c "jackd -r -ddummy -r44100 -p1024" &
        echo "Waiting for Jack..."
        sleep 5
      shell: bash

    - name: Debug Jack
      run: system_profiler -json | jq .SPAudioDataType
      shell: bash

