name: Publish
on:
  release:
    types: [released]

env:
  PYNPUT_BACKEND: dummy
  SC_ORIGIN: https://github.com/supercollider/supercollider.git
  SC_BRANCH: develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dist:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - name: Build
      run: uv build --clear --sdit --wheel
    - uses: actions/upload-artifact@v6
      with:
        name: dist
        path: ./dist

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Tune GitHub Actions
      uses: ./.github/actions/tune-github-actions
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - name: Setup audio
      uses: supriya-project/setup-audio@main
    - name: Setup SuperCollider
      uses: supriya-project/setup-supercollider@v1.1.1
      with:
        origin: ${{ env.SC_ORIGIN }}
        ref: ${{ env.SC_BRANCH }}
    - name: Install Supriya
      run: uv sync --extra docs
    - name: Install APT deps
      shell: bash
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame \
          libasound2-dev
    - name: Build docs
      run: uv run make docs
    - uses: actions/upload-artifact@v6
      with:
        name: docs
        path: ./docs/build/html/

  upload-to-testpypi:
    name: Publish release to Test PyPI
    environment: testpypi
    needs: [build-dist, build-docs]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v7
      with:
        path: dist
        pattern: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  upload-to-pypi:
    name: Publish release to PyPI
    environment: pypi
    needs: [upload-to-testpypi]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v7
      with:
        path: dist
        pattern: dist
    - uses: pypa/gh-action-pypi-publish@release/v1

  update-gh-pages:
    name: Update gh-pages
    needs: [upload-to-pypi]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v7
      with:
        name: docs
        path: docs
    - name: Clone gh-pages
      uses: actions/checkout@v6
      with:
        path: gh-pages
        ref: gh-pages
    - name: Rsync docs
      run: rsync -rtv --del --exclude=.git docs/ gh-pages/
    - name: Touch .nojekyll
      run: touch gh-pages/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        allow_empty_commit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
