name: Publish
on:
  release:
    types: [released]

env:
  PYNPUT_BACKEND: dummy
  SC_ORIGIN: https://github.com/supercollider/supercollider.git
  SC_BRANCH: develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Tune GitHub Actions
      uses: ./.github/actions/tune-github-actions
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - name: Setup audio
      uses: supriya-project/setup-audio@main
    - name: Setup SuperCollider
      uses: supriya-project/setup-supercollider@v1.1.1
      with:
        origin: ${{ env.SC_ORIGIN }}
        ref: ${{ env.SC_BRANCH }}
    - name: Install Supriya
      run: uv sync --extra docs
    - name: Install APT deps
      shell: bash
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame \
          libasound2-dev
    - name: Build docs
      run: uv run make docs
    - uses: actions/upload-artifact@v6
      with:
        name: docs
        path: ./docs/build/html/

  build-wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - {os: macos-15,         arch: "arm64,x86_64", build: "cp3{10,11,12,13,14}-*",          dist: "macos"}
        - {os: ubuntu-24.04,     arch: auto,           build: "cp3{10,11,12,13,14}-manylinux*", dist: "manylinux-amd"}
        - {os: ubuntu-24.04,     arch: auto,           build: "cp3{10,11,12,13,14}-musllinux*", dist: "musllinux-amd"}
        - {os: ubuntu-24.04-arm, arch: auto,           build: "cp3{10,11,12,13,14}-manylinux*", dist: "manylinux-arm"}
        - {os: ubuntu-24.04-arm, arch: auto,           build: "cp3{10,11,12,13,14}-musllinux*", dist: "musllinux-arm"}
        - {os: windows-latest,   arch: AMD64,          build: "cp3{10,11,12,13,14}-*",          dist: "windows-amd"}
        - {os: windows-latest,   arch: ARM64,          build: "cp3{10,11,12,13,14}-*",          dist: "windows-arm"}
    steps:
    - uses: actions/checkout@v6
    - env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.build }}
      name: Build wheels
      uses: pypa/cibuildwheel@v3.4.0
    - name: Upload wheels 
      uses: actions/upload-artifact@v6
      with:
        name: dist-${{ matrix.dist }}
        path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build sdist
      run: pipx run build --sdist
    - uses: actions/upload-artifact@v6
      with:
        name: dist-sdist
        path: dist/*.tar.gz

  upload-to-pypi:
    name: Publish release to PyPI
    environment: release
    needs: [build-wheels, build-sdist, build-docs]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v7
      with:
        merge-multiple: true
        path: dist
        pattern: dist-*
    - uses: pypa/gh-action-pypi-publish@release/v1

  update-gh-pages:
    name: Update gh-pages
    needs: [upload-to-pypi]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v7
      with:
        name: docs
        path: docs
    - name: Clone gh-pages
      uses: actions/checkout@v6
      with:
        path: gh-pages
        ref: gh-pages
    - name: Rsync docs
      run: rsync -rtv --del --exclude=.git docs/ gh-pages/
    - name: Touch .nojekyll
      run: touch gh-pages/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        allow_empty_commit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
