name: Release

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}"

env:
  GH_TOKEN: "${{ github.token }}"

jobs:

  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: "3.14"
        enable-cache: false
    - name: Get latest version
      run: echo OLD_VERSION=$(gh release list -L 1 --json name | jq -r '.[0].name') >> $GITHUB_ENV
    - name: Bump version file
      run: echo NEW_VERSION=$(uv run dev/bump-version.py ${OLD_VERSION}) >> $GITHUB_ENV
    - name: Debug
      run: |
        echo ${OLD_VERSION}
        echo ${NEW_VERSION}
    - name: Push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "Bump version to ${NEW_VERSION}"
        git push
    - name: Create release
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        draft: true
        generate_release_notes: true
        name: "${{ env.NEW_VERSION }}"
        tag_name: "v${{ env.NEW_VERSION }}"
