name: Test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: "0 0 * * 0"

env:
  PYNPUT_BACKEND: dummy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-dist:
    name: Build distribution archives
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - run: uv build --clear --sdist --wheel

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/tune-github-actions
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - uses: supriya-project/setup-audio@main
    - uses: supriya-project/setup-supercollider@v1.1.1
    - name: Install Supriya
      run: uv sync --extra docs
    - name: Install APT deps
      shell: bash
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame \
          libasound2-dev
    - name: Build docs
      run: uv run make docs
    - name: Check for FailWarning
      run: "! grep -R ': FailWarning: ' *"
      working-directory: docs/build/html
    - name: Link check
      run: uv run make linkcheck
      working-directory: docs
  
  lint:
    name: Lint Supriya
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
    - name: Install Supriya
      run: uv sync --extra test
    - name: Run Ruff format checker
      run: uv run make ruff-format
    - name: Run Ruff imports checker
      run: uv run make ruff-imports
    - name: Run Ruff lint checker
      run: uv run make ruff-lint
    - name: Run Mypy
      run: uv run make mypy

  test:
    name: Test Supriya
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
        - {os: macos-15,       python-version: "3.14"}
        - {os: windows-latest, python-version: "3.14"}
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v6
    - name: Tune GitHub Actions
      uses: ./.github/actions/tune-github-actions
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "${{ matrix.python-version }}"
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - uses: supriya-project/setup-audio@main
    - uses: supriya-project/setup-supercollider@v1.1.1
    - name: Install Supriya
      run: uv sync
    - name: Sanity-check Supriya
      run: |
        uv run python -c "import logging, supriya; logging.getLogger('supriya').setLevel(logging.INFO); logging.basicConfig(); server = supriya.Server().boot(); exit()"
      timeout-minutes: 1
    - name: Check for stray processes (Non-Windows)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        ! ( ps aux | grep scsynth | grep -v grep )
        ! ( ps aux | grep supernova | grep -v grep )
    - name: Install Supriya test dependencies
      run: uv sync --extra test
    - name: Install additional packages
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update --yes
          sudo apt-get install --yes espeak ffmpeg graphviz lame libasound2-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew update
          brew install ffmpeg graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install ffmpeg graphviz lame
        fi
    - name: Run Pytest
      run: uv run pytest --cov supriya --showlocals
      timeout-minutes: 15
    - name: Check for stray processes (Non-Windows)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        ! ( ps aux | grep scsynth | grep -v grep )
        ! ( ps aux | grep supernova | grep -v grep )
