name: Test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: "0 0 * * 0"

env:
  PYNPUT_BACKEND: dummy
  SC_ORIGIN: https://github.com/supercollider/supercollider.git
  SC_BRANCH: develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-docs:
    name: Build docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.14"]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v6
    - name: Tune GitHub Actions
      uses: ./.github/actions/tune-github-actions
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "${{ matrix.python-version }}"
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - name: Setup audio
      timeout-minutes: 3
      uses: ./.github/actions/setup-audio
    - name: Install SuperCollider
      uses: supriya-project/setup-supercollider@v1.1.0
      with:
        origin: ${{ env.SC_ORIGIN }}
        ref: ${{ env.SC_BRANCH }}
    - name: Install Supriya
      run: uv sync --extra docs
    - name: Install APT deps
      shell: bash
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes \
          espeak \
          ffmpeg \
          graphviz \
          lame \
          libasound2-dev
    - name: Build docs
      run: uv run make docs
    - name: Check for FailWarning
      run: "! grep -R ': FailWarning: ' *"
      working-directory: docs/build/html
    - name: Link check
      run: uv run make linkcheck
      working-directory: docs
  
  lint:
    name: Lint Supriya
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.14"]
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install Supriya
      run: uv sync --extra test
    - name: Run Ruff format checker
      run: uv run make ruff-format
    - name: Run Ruff imports checker
      run: uv run make ruff-imports
    - name: Run Ruff lint checker
      run: uv run make ruff-lint
    - name: Run Mypy
      run: uv run make mypy

  package:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: macos-15,         arch: "arm64,x86_64", build: "cp3{10,11,12,13,14}-*"}
        - {os: ubuntu-24.04,     arch: auto,           build: "cp3{10,11,12,13,14}-manylinux*"}
        - {os: ubuntu-24.04,     arch: auto,           build: "cp3{10,11,12,13,14}-musllinux*"}
        - {os: ubuntu-24.04-arm, arch: auto,           build: "cp3{10,11,12,13,14}-manylinux*"}
        - {os: ubuntu-24.04-arm, arch: auto,           build: "cp3{10,11,12,13,14}-musllinux*"}
        - {os: windows-latest,   arch: AMD64,          build: "cp3{10,11,12,13,14}-*"}
        - {os: windows-latest,   arch: ARM64,          build: "cp3{10,11,12,13,14}-*"}
    steps:
    - uses: actions/checkout@v6
    - name: Build wheels
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.build }}
      uses: pypa/cibuildwheel@v3.4.0

  test:
    name: Test Supriya
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
        - {os: macos-15,       python-version: "3.14"}
        - {os: windows-latest, python-version: "3.14"}
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v6
    - name: Tune GitHub Actions
      uses: ./.github/actions/tune-github-actions
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "${{ matrix.python-version }}"
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - name: Setup audio
      timeout-minutes: 3
      uses: ./.github/actions/setup-audio
    - name: Install SuperCollider
      uses: supriya-project/setup-supercollider@v1.1.0
      with:
        origin: ${{ env.SC_ORIGIN }}
        ref: ${{ env.SC_BRANCH }}
    - name: Install Supriya
      run: uv sync
    - name: Sanity-check Supriya
      run: |
        uv run python -c "import logging, supriya; logging.getLogger('supriya').setLevel(logging.INFO); logging.basicConfig(); server = supriya.Server().boot(); exit()"
        uv run python -c "from supriya.contexts.shm import ServerSHM; print(ServerSHM)"
      timeout-minutes: 1
    - name: Check for stray processes (Non-Windows)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        ! ( ps aux | grep scsynth | grep -v grep )
        ! ( ps aux | grep supernova | grep -v grep )
    - name: Install Supriya test dependencies
      run: uv sync --extra test
    - name: Install additional packages
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update --yes
          sudo apt-get install --yes espeak ffmpeg graphviz lame libasound2-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew update
          brew install ffmpeg graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install ffmpeg graphviz lame
        fi
    - name: Run Pytest
      run: uv run pytest --cov supriya --showlocals
      timeout-minutes: 15
    - name: Check for stray processes (Non-Windows)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        ! ( ps aux | grep scsynth | grep -v grep )
        ! ( ps aux | grep supernova | grep -v grep )
